name: The First Pulse

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Greeting Test
        run: echo "Hello DevSecOps!"
        